# Generated by Django 3.0.4 on 2020-04-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDescription',
            field=models.CharField(default=None, max_length=5000, null=True, verbose_name='course description'),
        ),
    ]
