# Generated by Django 3.0.4 on 2020-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0002_auto_20200420_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=200, verbose_name='class name')),
                ('classInstitution', models.CharField(max_length=200, null=True, verbose_name='institution')),
                ('courses', models.ManyToManyField(to='accountManagement.Course')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(to='accountManagement.StudentClass'),
        ),
    ]
