# Generated by Django 2.2.9 on 2020-05-21 03:46

import StarHorizonElearning.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0003_auto_20200425_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, storage=StarHorizonElearning.storage_backends.MediaStorage(), upload_to='', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, to='accountManagement.StudentClass'),
        ),
    ]
