# Generated by Django 2.2.9 on 2020-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0004_auto_20200521_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='courses',
            field=models.ManyToManyField(blank=True, to='accountManagement.Course'),
        ),
    ]
