# Generated by Django 2.2.9 on 2020-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0005_auto_20200523_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='courses',
            field=models.ManyToManyField(to='accountManagement.Course'),
        ),
    ]
