# Generated by Django 2.2.9 on 2020-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0006_auto_20200606_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizResponses',
            field=models.CharField(max_length=1000000000, null=True, verbose_name='quizResponses'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='courses',
            field=models.ManyToManyField(blank=True, to='accountManagement.Course'),
        ),
    ]
