# Generated by Django 2.2.9 on 2020-07-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0007_auto_20200608_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=200, verbose_name='module name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Course')),
            ],
        ),
    ]
