# Generated by Django 2.2.9 on 2020-07-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0008_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='courses',
        ),
    ]
