# Generated by Django 2.2.9 on 2020-07-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0009_auto_20200718_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quizTags',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
