# Generated by Django 2.2.9 on 2020-08-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0010_course_quiztags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': 'Student Classes'},
        ),
    ]
