# Generated by Django 2.2.9 on 2020-08-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0012_auto_20200815_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
