# Generated by Django 2.2.9 on 2020-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0016_auto_20201018_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeOnline',
            field=models.DurationField(blank=True, null=True, verbose_name='timeOnline'),
        ),
    ]
