# Generated by Django 2.2.9 on 2021-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0018_auto_20210610_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
