# Generated by Django 2.2.9 on 2022-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0019_auto_20210610_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notificationAccess',
            field=models.BooleanField(default=False),
        ),
    ]
