# Generated by Django 2.2.9 on 2022-03-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220304_0519'),
        ('accountManagement', '0021_auto_20220304_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notificationsSeen',
            field=models.ManyToManyField(to='notifications.Notification'),
        ),
    ]
