# Generated by Django 2.2.9 on 2022-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0022_user_notificationsseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='quizTags',
        ),
        migrations.AddField(
            model_name='user',
            name='pwResetCode',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='pwResetTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='users', to='accountManagement.StudentClass'),
        ),
    ]
