# Generated by Django 2.2.9 on 2020-07-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountManagement', '0009_auto_20200718_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=200, verbose_name='lesson name')),
                ('lessonDesc', models.CharField(max_length=500, verbose_name='lesson description')),
                ('streamID', models.CharField(max_length=200, verbose_name='stream id')),
                ('streamTime', models.DateTimeField()),
                ('streamDuration', models.DurationField()),
                ('streamEndTime', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Module')),
            ],
        ),
    ]
