# Generated by Django 2.2.9 on 2020-09-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0015_auto_20200906_2304'),
        ('liveLesson', '0002_livelesson_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livelesson',
            name='module',
        ),
        migrations.AddField(
            model_name='livelesson',
            name='studentClass',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='accountManagement.StudentClass'),
            preserve_default=False,
        ),
    ]
