# Generated by Django 3.0.5 on 2020-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=200, verbose_name='video name')),
                ('videoID', models.CharField(max_length=200, verbose_name='video id')),
                ('additionalComments', models.CharField(max_length=5000, null=True, verbose_name='additional comments')),
                ('videoURL', models.CharField(max_length=1000, null=True, verbose_name='video url')),
                ('completeionURL', models.CharField(max_length=1000, null=True, verbose_name='url to go to after completion')),
            ],
        ),
    ]
