# Generated by Django 2.2.9 on 2020-09-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoLessons', '0007_video_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='afterAction',
            field=models.CharField(max_length=200, null=True, verbose_name='action to take after video'),
        ),
    ]
