# Generated by Django 2.2.9 on 2022-07-10 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_clone.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountManagement', '0023_auto_20220710_1359'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=999, null=True, verbose_name='Question Text')),
                ('autoGrade', models.BooleanField(default=False)),
                ('optionOrder', models.CharField(default='[]', max_length=9999, verbose_name='Option Order')),
                ('type', models.CharField(choices=[('cb', 'Checkboxes'), ('mc', 'Multiple Choice'), ('sa', 'Short Answer'), ('la', 'Long Answer')], default='cb', max_length=8)),
                ('saAnswer', models.CharField(default='', max_length=999)),
                ('mcAnswer', models.IntegerField(default=-1)),
                ('cbAnswer', models.CharField(default='[]', max_length=999)),
                ('name', models.CharField(default='', max_length=999, verbose_name='Question Name')),
                ('isBankQuestion', models.BooleanField(default=False)),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=200, verbose_name='quiz name')),
                ('quizID', models.CharField(max_length=200, verbose_name='quiz id')),
                ('quizDueDate', models.DateTimeField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('passingScore', models.IntegerField(blank=True, default=0, null=True, verbose_name='passing score')),
                ('repeatNumber', models.IntegerField(default=0, verbose_name='repeat number')),
                ('questionOrder', models.CharField(default='[]', max_length=9999, verbose_name='Question Order')),
                ('randomOptions', models.IntegerField(default=False, verbose_name='randomise options')),
                ('randomQuestions', models.IntegerField(default=False, verbose_name='randomise questions')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Module')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizAttempts', to='quizzes.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=999)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionTags', to='accountManagement.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cb', 'Checkboxes'), ('mc', 'Multiple Choice'), ('sa', 'Short Answer'), ('la', 'Long Answer')], default='cb', max_length=8)),
                ('saAnswer', models.CharField(default='', max_length=999999)),
                ('mcAnswer', models.IntegerField(default=-1)),
                ('cbAnswer', models.CharField(default='[]', max_length=999)),
                ('isCorrect', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionAttempts', to='quizzes.Question')),
                ('quizAttempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionAttempts', to='quizzes.QuizAttempt')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.QuestionTag'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.Quiz'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=999, null=True, verbose_name='Option text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.Question')),
            ],
        ),
    ]
