# Generated by Django 2.2.9 on 2020-05-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=200, verbose_name='quiz name')),
                ('quizID', models.CharField(max_length=200, verbose_name='quiz ID')),
                ('quizData', models.CharField(max_length=100000, verbose_name='quiz ID')),
            ],
        ),
    ]
