# Generated by Django 2.2.9 on 2020-05-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0004_auto_20200521_1146'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Course'),
            preserve_default=False,
        ),
    ]
