# Generated by Django 2.2.9 on 2020-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizData',
            field=models.CharField(max_length=100000, verbose_name='quiz data'),
        ),
    ]
