# Generated by Django 2.2.27 on 2023-02-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20220916_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='timestamp',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='quizzes.QuizImage'),
        ),
    ]
