# Generated by Django 2.2.9 on 2020-05-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20200521_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizDueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
