# Generated by Django 2.2.27 on 2023-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20230217_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allowRetries',
            field=models.IntegerField(default=False, verbose_name='allow retries'),
        ),
    ]
