# Generated by Django 2.2.9 on 2020-05-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_quizduedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quizID',
        ),
    ]
