# Generated by Django 2.2.27 on 2023-07-14 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20230715_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 21, 21, 38, 309646, tzinfo=utc)),
        ),
    ]
