# Generated by Django 2.2.9 on 2020-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_quiz_quizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizData',
            field=models.CharField(max_length=10000000, verbose_name='quiz data'),
        ),
    ]
