# Generated by Django 2.2.9 on 2020-06-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20200606_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizID',
            field=models.CharField(default='', max_length=200, verbose_name='quiz id'),
            preserve_default=False,
        ),
    ]
