# Generated by Django 2.2.27 on 2023-07-14 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20230715_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
