# Generated by Django 2.2.27 on 2023-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20230715_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
