# Generated by Django 2.2.9 on 2020-07-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20200719_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='course',
            new_name='module',
        ),
    ]
