# Generated by Django 2.2.9 on 2020-08-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20200720_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
