# Generated by Django 2.2.9 on 2020-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='repeatNumber',
            field=models.IntegerField(default=0, verbose_name='repeat number'),
            preserve_default=False,
        ),
    ]
