# Generated by Django 2.2.9 on 2020-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_quiz_repeatnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passingScore',
            field=models.IntegerField(blank=True, null=True, verbose_name='passing score'),
        ),
    ]
