# Generated by Django 2.2.9 on 2021-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_quiz_passingscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionName', models.CharField(max_length=200, verbose_name='quiz name')),
                ('questionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('quizData', models.CharField(max_length=10000000, verbose_name='quiz data')),
            ],
            options={
                'verbose_name_plural': 'Question bank questions',
            },
        ),
    ]
