# Generated by Django 2.2.9 on 2021-06-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='BankQuestion',
        ),
        migrations.AlterModelOptions(
            name='bankquestion',
            options={},
        ),
    ]
