# Generated by Django 2.2.9 on 2021-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_auto_20210610_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankquestion',
            name='questionId',
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
