# Generated by Django 2.2.9 on 2021-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_auto_20210610_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankquestion',
            name='quizData',
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='questionData',
            field=models.CharField(default='', max_length=10000000, verbose_name='question data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankquestion',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='bankquestion',
            name='questionName',
            field=models.CharField(max_length=200, verbose_name='question name'),
        ),
    ]
