# Generated by Django 2.2.9 on 2021-06-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_auto_20210610_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankQuestion',
        ),
    ]
