# Generated by Django 2.2.9 on 2021-06-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_delete_bankquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionName', models.CharField(max_length=200, verbose_name='question name')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('questionData', models.CharField(max_length=10000000, verbose_name='question data')),
            ],
        ),
    ]
