# Generated by Django 2.2.9 on 2021-06-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0019_auto_20210610_2050'),
        ('quizzes', '0019_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=200, verbose_name='quiz name')),
                ('quizID', models.CharField(max_length=200, verbose_name='quiz id')),
                ('quizDueDate', models.DateTimeField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('passingScore', models.IntegerField(blank=True, null=True, verbose_name='passing score')),
                ('quizData', models.CharField(max_length=10000000, verbose_name='quiz data')),
                ('repeatNumber', models.IntegerField(verbose_name='repeat number')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Module')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
