# Generated by Django 2.2.9 on 2021-06-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_quiz2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz2',
        ),
    ]
