# Generated by Django 2.2.9 on 2021-06-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_auto_20210611_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
