# Generated by Django 2.2.9 on 2021-06-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
