# Generated by Django 2.2.9 on 2021-08-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_auto_20210703_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionTitle',
            field=models.CharField(default='question title not updated yet, please delete question and add it again', max_length=2000, verbose_name='question title'),
            preserve_default=False,
        ),
    ]
