from django.urls import path

from . import views

urlpatterns = [
    path("manage/", views.manageQuizzes, name="Manage Quizzes"),
    path("create/", views.createQuiz, name="Create Quiz"),
    path("setImage/", views.setImage, name="Set Image"),
    path("deleteImage/", views.deleteImage, name="Delete Image"),
    path("<str:quizID>/edit/", views.editQuiz, name="Edit Quiz"),
    path("<str:quizID>/do/", views.doQuiz, name="Do Quiz"),
    path("<str:quizID>/duplicate/", views.duplicateQuiz, name="Duplicate Quiz"),
    path("<str:quizID>/delete/", views.deleteQuiz, name="Delete Quiz"),
    path(
        "<str:quizID>/edit/settings/", views.editQuizSettings, name="Edit Quiz Settings"
    ),
    path("<str:quizID>/get/", views.getQuiz, name="Get Quiz"),
    path("<str:quizID>/doGet/", views.getQuizDo, name="Get Quiz Do"),
    path("<str:quizID>/submit/", views.submit, name="Submit"),
    path("<str:quizID>/getAttempt/", views.getAttempt, name="Get Attempt"),
    path("<str:quizID>/addQuestion/", views.addQuestion, name="Add Question"),
    path("<str:quizID>/getQuestions/", views.getQuestions, name="Get Questions"),
    path("<str:quizID>/254d285e-5d14-4460-a108-30c87b3904d6/", views.clearCbOptions),
    path("<str:quizID>/addBank/<int:questionID>/",
         views.addBank, name="Add Bank"),
    path("getModules/", views.getModules, name="Get Modules"),
    path("getCourses/", views.getCourses, name="Get Courses"),
    path("deleteQuestion/", views.deleteQuestion, name="Delete Question"),
    path("editQuestion/", views.editQuestion, name="Edit Question"),
    path("addOption/", views.addOption, name="Add Option"),
    path("getOptions/", views.getOptions, name="Get Options"),
    path("editOption/", views.editOption, name="Edit Options"),
    path("deleteOption/", views.deleteOption, name="Delete Option"),
    path("cbValidation/", views.cbValidation, name="cb Validation"),
    path('download/', views.downloadQuiz, name='downloadQuiz'),
    path('dl/', views.exportQuiz, name='downloadQuiz'),
    path('createTag/<str:courseID>/', views.createTag, name="Create Tag"),
    path('deleteTag/<int:tagID>/', views.deleteTag, name="Delete Tag"),
    path('getTags/', views.getTags, name="Get Tags"),
    path('bank/', views.questionBank, name="Question Bank"),
    path('bank/getBank/', views.getBank, name="Question Bank"),
    path('createBank/', views.createBank, name="Create Bank"),
    path('bank/<int:questionID>/getQuestion/',
         views.getQuestion, name="Get question"),
    path('bank/<int:questionID>/delete/',
         views.deleteQuestionBank, name="Get question"),
    path('bank/<int:questionID>/edit/',
         views.editBank, name="Edit question"),
]
