# Generated by Django 2.2.9 on 2020-07-15 15:02

import StarHorizonElearning.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200, verbose_name='file name')),
                ('filID', models.CharField(max_length=200, verbose_name='file id')),
                ('uploadedFile', models.FileField(storage=StarHorizonElearning.storage_backends.MediaStorage(), upload_to='')),
            ],
        ),
    ]
