# Generated by Django 2.2.9 on 2020-08-30 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileUploads', '0003_fileupload_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
