# Generated by Django 2.2.9 on 2022-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountManagement', '0020_user_notificationaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.CharField(max_length=999999, verbose_name='content')),
                ('studentClass', models.ManyToManyField(to='accountManagement.StudentClass')),
            ],
        ),
    ]
