# Generated by Django 2.2.27 on 2022-06-06 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20220606_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 13, 38, 36, 721862)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 13, 38, 36, 721862)),
        ),
    ]
