# Generated by Django 2.2.9 on 2022-07-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_auto_20220612_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
