# Generated by Django 2.2.9 on 2022-07-10 05:59

import StarHorizonElearning.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountManagement', '0023_auto_20220710_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='lesson name')),
                ('fileID', models.CharField(max_length=200, verbose_name='file id')),
                ('uploadedFile', models.FileField(storage=StarHorizonElearning.storage_backends.MediaStorage(), upload_to='')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountManagement.Module')),
            ],
        ),
    ]
