# Generated by Django 2.2.9 on 2022-07-18 13:19

import StarHorizonElearning.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='uploadedFile',
            field=models.FileField(storage=StarHorizonElearning.storage_backends.H5PStorage(), upload_to=''),
        ),
    ]
